### ISSUE TITLE
Podge can't be installed from opam

### ISSUE THREAD

**Issue by whirm** [fxfactorial/podge#4]
```
$ opam install podge
Sorry, no solution found: there seems to be a problem with your request.
```

This is with ocaml `4.04.0`

Thanks!

**Comment by fxfactorial** [comment]
hi, thanks for the report, can you also run it with: 

`OPAMVERBOSE=1` as an environment variable?

**Comment by fxfactorial** [comment]
@whirm Hi, I just cut a new release, you should try it once this PR is accepted: https://github.com/ocaml/opam-repository/pull/8165

**Comment by whirm** [comment]
Thanks! I'll check it out later today when I'm on my personal laptop (and post the output with OPAMVERBOSE if it still fails).

**Comment by whirm** [comment]
It work now. Thanks!
